apiVersion: v1
kind: Service
metadata:
  name: eks-argocd-app-service # Fixed spelling: 'arocd' -> 'argocd'
  namespace: default
spec:
  type: LoadBalancer # Changed from ClusterIP to LoadBalancer for a public AWS URL
  selector:
    app: eks-argocd-app # Fixed spelling to exactly match your running deployment pods
  ports:
    - protocol: TCP
      port: 80         # The port you will type into your browser
      targetPort: 8086 # Your internal Spring Boot app port
      
