apiVersion: v1
kind: Service
metadata:
  name: eks-arocd-app-service
  namespace: default
spec:
  type: ClusterIP # Use 'LoadBalancer' instead if you want AWS to generate a public URL
  selector:
    app: eks-arocd-app # Must match the label in the deployment file
  ports:
    - protocol: TCP
      port: 80        # The port exposed outside the cluster (e.g., http://service-ip:80)
      targetPort: 8086 # The internal port your Spring Boot container is listening on